// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Julio_Cesar.DAL;

namespace P2_AP1_Julio_Cesar.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211109011322_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Julio_Cesar.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecripcionProyecto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("P2_AP1_Julio_Cesar.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTareaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoTareaId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("P2_AP1_Julio_Cesar.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acomulado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecripcionTipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoTareaId");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoTareaId = 1,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoTareaId = 2,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoTareaId = 3,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Programacion"
                        },
                        new
                        {
                            TipoTareaId = 4,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_Julio_Cesar.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("P2_AP1_Julio_Cesar.Entidades.Proyectos", "proyecto")
                        .WithMany("Detalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2_AP1_Julio_Cesar.Entidades.TiposTareas", "TiposTareas")
                        .WithMany()
                        .HasForeignKey("TipoTareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proyecto");

                    b.Navigation("TiposTareas");
                });

            modelBuilder.Entity("P2_AP1_Julio_Cesar.Entidades.Proyectos", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
