// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Julio_Cesar.DAL;

namespace P2_AP1_Julio_Cesar.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211108222651_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Julio_Cesar.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acomulado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecripcionTipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoTareaId");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoTareaId = 1,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoTareaId = 2,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoTareaId = 3,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Programacion"
                        },
                        new
                        {
                            TipoTareaId = 4,
                            Acomulado = 0,
                            DecripcionTipoTarea = "Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
